---
title: "ARMA Hilfsfunktion"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(grid)
library(rlist)
library(forecast)
```

```{r}
plot_acf <- function(throughputs, type = c("acf", "pacf"), 
                     title="Autokorrelationsfunktionen"){
  
  grid.newpage()
  pushViewport(viewport(
    layout=grid.layout(3,2, heights = unit(c(1, 5, 5), "null"))))
  
  if (type == "acf") {
    chosen_func <- ggAcf
    grid.text(title, gp=gpar(fontsize=20),
              vp = viewport(layout.pos.row = 1, layout.pos.col = 1:2))
    }
  else {
    chosen_func <- ggPacf
    grid.text(title, gp=gpar(fontsize=20),
              vp = viewport(layout.pos.row = 1, layout.pos.col = 1:2))
    }
  
  vodafone_plot <- chosen_func(throughputs$vodafone) + 
    ggtitle("Vodafone") + ylab("Korrelation") + theme_grey(base_size = 16)
  tmobile_plot <- chosen_func(throughputs$tmobile) + ggtitle("T-Mobile") + 
    ylab("Korrelation") + theme_grey(base_size = 16)
  o2_plot <- chosen_func(throughputs$o2) + ggtitle("O2") + ylab("Korrelation") + 
    theme_grey(base_size = 16)
  
  print(vodafone_plot, vp=viewport(layout.pos.row = 2, layout.pos.col = 1))
  print(tmobile_plot, vp=viewport(layout.pos.row = 2, layout.pos.col = 2))
  print(o2_plot, vp=viewport(layout.pos.row = 3, layout.pos.col = 1))
  
}
```